all: compile

compile:
	echo "========================";
	cd server && go build . && mv server ../bin/reporter;
	echo "========================";
	
	

clean:
	echo "good"





test: test_handler




test_handler:
	go test -v -count=1 ./data_fetcherconf;